### ISSUE TITLE
photo url

### ISSUE THREAD

**Issue by cen6wkf** [fatimaazfar/Google-Maps-Scraper#1]
Hi fatimaazfar,

Great work!

May I know how to extract the url to the most representative photo of the place also?

**Comment by fatimaazfar** [comment]
Hi there! I somehow never came across your comment, sorry about that. 
To get an image, you can simply inspect the webpage, use the element selection tool on the inspect window to see the element affiliated with the image, and fetch that either by taking a screenshot of the element or by simply downloading it using the requests library:
Screenshot the element:
element = driver.find_element_by_id('element_id')  # Find the element
element.screenshot('element_screenshot.png')  # Save screenshot of the element
Download the image:
image = driver.find_element_by_xpath('xpath_of_the_image')
image_url = image.get_attribute('src')
response = requests.get(image_url)
if response.status_code == 200:
    with open('image.png', 'wb') as file:
        file.write(response.content)
